baseURL = "https://andreasflakstad.no/"
languageCode = "en-us"
title = "Andreas Flakstad"
theme = "PaperMod"

# Pagination (new syntax in Hugo v0.128+)
[pagination]
  pagerSize = 10

[params]
  # General
  author = "Andreas Flakstad"
  defaultTheme = "auto"      # or "dark", or "auto"
  disableThemeToggle = true   # hide the dark/light switch
  #customCSS = ["css/custom.css"]

  # Blog behavior
  showReadingTime = false
  showPostNavLinks = true
  showBreadCrumbs = false
  showShareButtons = false
  showCodeCopyButtons = false

  # Footer
  hideFooter = true
  hideCredits = true
